# Generated by Django 2.2.5 on 2019-11-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_video_downloading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
