# Generated by Django 2.2.5 on 2019-11-08 08:46

from django.db import migrations, models
import post_video_downloading.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_video_downloading', '0002_auto_20191108_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='message',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=post_video_downloading.models.user_directory_path),
        ),
    ]
